# -*- coding: utf-8 -*-
"""LabTask:1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEBagQOY2GQZDSyJ0KAnEZ1oPsvizDhb
"""

print("Hello, World!")

name = input("Enter your name: ")
print(f"Hello, {name}!")

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

sum_result = num1 + num2
diff_result = num1 - num2
product_result = num1 * num2
if num2 != 0:
    quotient_result = num1 / num2
else:
    quotient_result = "Undefined (division by zero)"

print("Sum:", sum_result)
print("Difference:", diff_result)
print("Product:", product_result)
print("Quotient:", quotient_result)

number = int(input("Enter a number: "))

if number % 2 == 0:
    print(f"{number} is Even.")
else:
    print(f"{number} is Odd.")

squares = []

for i in range(1, 11):
    squares.append(i ** 2)

print("List of squares from 1 to 10:", squares)

numbers = [5, 3, 8, 1]

print("Original list:", numbers)

numbers.append(10)
print("After adding 10:", numbers)

numbers.remove(3)
print("After removing 3:", numbers)

numbers.sort()
print("Sorted list:", numbers)

students = {
    "Ali": 85,
    "Sara": 90,
    "Ahmed": 78
}

print("Original dictionary:", students)

students["Zara"] = 88
print("After adding Zara:", students)

students["Sara"] = 95
print("After updating Sara's marks:", students)

del students["Ahmed"]
print("After deleting Ahmed:", students)

def calculate_area(radius):
    pi = 3.14159
    area = pi * radius * radius
    return area

r = float(input("Enter the radius of the circle: "))
print("Area of the circle:", calculate_area(r))

add = lambda x, y: x + y

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("Sum using lambda:", add(num1, num2))

even_numbers = [x for x in range(1, 21) if x % 2 == 0]

print("Even numbers from 1 to 20:", even_numbers)